apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the database
    template.alpha.openshift.io/wait-for-ready: 'true'
  creationTimestamp: '2017-12-04T10:54:46Z'
  generation: 9
  labels:
    app: stairway-to-health
    template: nodejs-mongo-persistent
  name: stairway
  namespace: stage
  resourceVersion: '4576293'
  selfLink: /oapi/v1/namespaces/stage/deploymentconfigs/stairway
  uid: 8ae40bae-d8e1-11e7-8479-42010a840002
spec:
  replicas: 1
  selector:
    name: stairway
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: stairway
      name: stairway
    spec:
      containers:
        - env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: stairway-to-health
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: stairway-to-health
            - name: MONGODB_DATABASE
              value: stairway
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-admin-password
                  name: stairway-to-health
          image: >-
            centos/mongodb-32-centos7@sha256:0010b48c9abd1d3c89c653de1ea8ade49853c117bfbaca02d88068071e46e9dc
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 600
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p
                  $MONGODB_PASSWORD --eval="quit()"
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mongodb/data
              name: stairway-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: stairway-data
          persistentVolumeClaim:
            claimName: stairway
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - mongodb
        from:
          kind: ImageStreamTag
          name: 'mongodb:3.2'
          namespace: openshift
        lastTriggeredImage: >-
          centos/mongodb-32-centos7@sha256:0010b48c9abd1d3c89c653de1ea8ade49853c117bfbaca02d88068071e46e9dc
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 0
  conditions:
    - lastTransitionTime: '2018-01-22T10:34:51Z'
      lastUpdateTime: '2018-01-22T10:34:51Z'
      message: Deployment config does not have minimum availability.
      status: 'False'
      type: Available
    - lastTransitionTime: '2018-01-22T12:35:16Z'
      lastUpdateTime: '2018-01-22T12:35:16Z'
      message: replication controller "stairway-6" has failed progressing
      reason: ProgressDeadlineExceeded
      status: 'False'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 6
  observedGeneration: 9
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 0
